version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=dashboard-database-instance-1.cyo31ygmzfva.us-east-1.rds.amazonaws.com
      - DB_NAME=analytics
      - DB_USER=dbuser
      - DB_PASSWORD=Superman1262!
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_API_KEY=eyJrIjoieDVjV2wxQ3ViRVZUMGlOU0RVTEM5Zzk2SldUTml4Z0kiLCJuIjoiYWktZGFzaGJvYXJkLWNyZWF0b3IiLCJpZCI6MX0=
    depends_on:
      - grafana
    networks:
      - analytics-network

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=true
      - GF_FEATURE_TOGGLES_ENABLE=ngalert
      - GF_UNIFIED_ALERTING_ENABLED=true
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge

volumes:
  grafana-storage:
