apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    uid: PD8C576611E62080A
    url: db:5432
    user: dbuser
    secureJsonData:
      password: 03SVZH7GPGNbRxeX
    jsonData:
      database: analytics
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false
    editable: true
