version: '3.8'

services:
  web:
    build: 
      context: ..
      dockerfile: config/Dockerfile
    ports:
      - "80:80"
    env_file:
      - ../.env
    environment:
      - GRAFANA_URL=http://grafana:3000  # Internal Docker network
      - GRAFANA_EXTERNAL_URL=http://52.4.166.16:3000  # External frontend access
    depends_on:
      - grafana
    networks:
      - analytics-network

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=true
      - GF_FEATURE_TOGGLES_ENABLE=ngalert
      - GF_UNIFIED_ALERTING_ENABLED=true
    volumes:
      - analytics-dashboard_grafana-data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge

volumes:
  analytics-dashboard_grafana-data:
    external: true
